---
spring:
  config:
    activate:
      on-profile: aws-sqs-producer-local
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
# Embedded SQS reference: https://github.com/jojoldu/spring-boot-aws-mock
sqs:
  mock:
    enabled: true
  queues:
    -
      name: 'point-earn-dlq'
    -
      name: 'point-earn'
      defaultVisibilityTimeout: 10
      delay: 0
      receiveMessageWait: 0
      deadLettersQueue:
        name: "point-earn-dlq"
        maxReceiveCount: 5
    -
      name: 'point-cache'
    -
      name: 'point-redeem'
aws:
  sqs:
    queue:
      point-earn: 'point-earn'
      point-earn-dlq: 'point-earn-dlq'
      point-cache: 'point-cache'
      point-redeem: 'point-redeem'
---
spring:
  config:
    activate:
      on-profile: aws-sqs-consumer-local
cloud:
  aws:
    region:
      static: ap-northeast-2
sqs:
  mock:
    enabled: false
aws:
  sqs:
    queue:
      point-earn: 'point-earn'
      point-earn-dlq: 'point-earn-dlq'
      point-cache: 'point-cache'
      point-redeem: 'point-redeem'
