spring:
  application:
    name: point-api
  profiles:
    include:
      - db
      - server-port
      - aws-sqs
      - redis
    group:
      local: db-local,port-local,aws-sqs-producer-local,redis-local
      test: db-test
    active: local
