# 포인트 사용 API: POST /api/v1/points/redeem

### 포인트 사용 API 요청 성공: POST /api/v1/points/earn
POST {{point-api-host}}/api/v1/points/redeem
Content-Type: application/json
X_MEMBER_ID: 1

{
  "tradeId": "{{custom-trade-id}}",
  "eventType": "USE",
  "eventDetailType": "USE_BUY",
  "redeemPoint": -100,
  "description": "제품 A 구매"
}

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });

    client.test("Check data", function (){
        var jsonData = response.body
        client.assert(jsonData.code === "000")
        client.assert(jsonData.message === "정상 처리")
        client.assert(jsonData.data.eventType === "USE")
        client.assert(jsonData.data.eventDetailType === "USE_BUY")
    });
%}

### 포인트 사용 API 요청 실패(잔액부족): POST /api/v1/points/earn
POST {{point-api-host}}/api/v1/points/redeem
Content-Type: application/json
X_MEMBER_ID: 2

{
  "tradeId": "{{$uuid}}",
  "eventType": "USE",
  "eventDetailType": "USE_BUY",
  "redeemPoint": -50000,
  "description": "제품 B 구매"
}

> {%
    client.test("Status code is 400", function (){
        client.assert(response.status === 400, "Response status is not 400")
    });

    client.test("Check data", function (){
        var jsonData = response.body
        client.assert(jsonData.code === "P100")
        client.assert(jsonData.message === "잔액이 부족합니다.")
    });
%}
